<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>

        <ProjectReference Include="..\Woo.AICopilot.Core.AiGateway\Woo.AICopilot.Core.AiGateway.csproj"/>

        <ProjectReference Include="..\Woo.AICopilot.Core.DataAnalysis\Woo.AICopilot.Core.DataAnalysis.csproj" />

        <ProjectReference Include="..\Woo.AICopilot.Core.McpServer\Woo.AICopilot.Core.McpServer.csproj" />

        <ProjectReference Include="..\Woo.AICopilot.Core.Rag\Woo.AICopilot.Core.Rag.csproj" />

        <ProjectReference Include="..\Woo.AICopilot.SharedKernel\Woo.AICopilot.SharedKernel.csproj"/>
    </ItemGroup>
</Project>
